# Generated by Django 5.0.4 on 2024-04-25 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_category_tag_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_address",
            field=models.EmailField(
                max_length=254,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
