# Generated by Django 5.0.4 on 2024-04-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_user_email_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
