# Generated by Django 5.0.4 on 2024-04-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_item_cost_item_desired_stock_item_minimum_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
