# Generated by Django 5.0.4 on 2024-04-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_remove_item_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
