# Generated by Django 5.0.4 on 2024-04-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
