# Generated by Django 5.0.4 on 2024-04-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0010_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.CharField(max_length=100),
        ),
    ]
